; PlatformIO Project Configuration File
; MACROPAD BLE con HijelHID_BLEKeyboard (arregla HID en ESP32-C3)
; Plataforma pioarduino (Arduino 3.x + ESP-IDF 5.x) + NimBLE 2.x
[env:macropad-ble]
platform = https://github.com/pioarduino/platform-espressif32/archive/refs/tags/55.03.39.zip
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.mcu = esp32c3
lib_deps =
    hijelhub/HijelHID_BLEKeyboard
    h2zero/NimBLE-Arduino@^2.3.8
build_flags =
    -D CORE_DEBUG_LEVEL=0

